import {
  PDFDocument,
  PDFFont,
  PDFPage,
  rgb,
  StandardFonts,
} from "pdf-lib";
import type { CampaignRecord, SponsorRecord } from "./campaign.service";

// -- Layout constants ----------------------------------------------------------
const PAGE_W = 595.28;
const PAGE_H = 841.89;
const MARGIN = 40;
const CW = PAGE_W - MARGIN * 2; // content width

const C = {
  primary:  rgb(0.31, 0.18, 0.61),
  dark:     rgb(0.12, 0.12, 0.16),
  muted:    rgb(0.38, 0.38, 0.43),
  light:    rgb(0.95, 0.94, 0.98),
  border:   rgb(0.84, 0.82, 0.90),
  white:    rgb(1,    1,    1   ),
  green:    rgb(0.10, 0.45, 0.28),
};

// -- CO2 constants -------------------------------------------------------------
/** Average CO2 sequestered per tree per year (kg). */
const CO2_KG_PER_TREE_PER_YEAR = 20;

// -- Public types --------------------------------------------------------------

export interface SpeciesBreakdownEntry {
  species: string;
  count: number;
  co2KgPerYear: number;
}

export interface CampaignImpactReportInput {
  campaign: CampaignRecord;
  /**
   * Optional per-tree species data.  When omitted, tree count and CO2 are
   * derived from `campaign.treeCount` using the default rate.
   */
  speciesBreakdown?: SpeciesBreakdownEntry[];
  /**
   * Optional static map image (PNG/JPEG bytes) that is embedded in the report.
   * Must be = 2 MB.
   */
  locationMapBytes?: Uint8Array;
  locationMapFormat?: "png" | "jpg";
}

// -- Helpers -------------------------------------------------------------------

function trunc(s: string, max: number): string {
  return s.length <= max ? s : `${s.slice(0, max - 1)}\u2026`;
}

function drawRule(page: PDFPage, y: number): void {
  page.drawLine({
    start: { x: MARGIN, y },
    end:   { x: PAGE_W - MARGIN, y },
    thickness: 1,
    color: C.border,
  });
}

function drawHeader(page: PDFPage, bold: PDFFont, regular: PDFFont): number {
  page.drawRectangle({ x: 0, y: PAGE_H - 88, width: PAGE_W, height: 88, color: C.primary });
  page.drawText("Fundable Protocol", {
    x: MARGIN, y: PAGE_H - 40, font: bold, size: 20, color: C.white,
  });
  page.drawText("CAMPAIGN IMPACT REPORT", {
    x: MARGIN, y: PAGE_H - 60, font: regular, size: 9, color: rgb(0.88, 0.84, 0.96),
  });
  return PAGE_H - 108;
}

function drawFooter(page: PDFPage, regular: PDFFont, pageNum: number): void {
  page.drawRectangle({ x: 0, y: 0, width: PAGE_W, height: 26, color: C.light });
  page.drawText("Generated by Fundable Protocol", {
    x: MARGIN, y: 8, font: regular, size: 7, color: C.muted,
  });
  const pg = `Page ${pageNum}`;
  page.drawText(pg, {
    x: PAGE_W - MARGIN - regular.widthOfTextAtSize(pg, 7),
    y: 8, font: regular, size: 7, color: C.muted,
  });
}

function statCard(
  page: PDFPage,
  bold: PDFFont,
  regular: PDFFont,
  x: number,
  y: number,
  w: number,
  label: string,
  value: string,
  valueColor = C.primary,
): void {
  page.drawRectangle({ x, y: y - 46, width: w, height: 46, color: C.light, borderColor: C.border, borderWidth: 1 });
  page.drawText(label,  { x: x + 10, y: y - 16, font: regular, size: 7,  color: C.muted });
  page.drawText(trunc(value, 18), { x: x + 10, y: y - 34, font: bold,    size: 13, color: valueColor });
}

// -- Main export ---------------------------------------------------------------

/**
 * Generate a campaign impact report PDF.
 *
 * The report includes:
 *   - Campaign headline (name, status, location)
 *   - Summary stat cards (trees, CO2, sponsors, raised/goal)
 *   - Species breakdown table
 *   - Sponsor list (up to 200 rows, then truncated)
 *   - Optional embedded location map image
 *
 * Issue #985.
 */
export async function buildCampaignImpactReportPdf(
  input: CampaignImpactReportInput,
  generatedAt = new Date(),
): Promise<Uint8Array> {
  const { campaign } = input;

  const pdf = await PDFDocument.create();
  pdf.setTitle(`${campaign.name} — Impact Report`);
  pdf.setAuthor("Fundable Protocol");
  pdf.setSubject("Campaign impact: trees, CO2, sponsors");
  pdf.setCreationDate(generatedAt);

  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold    = await pdf.embedFont(StandardFonts.HelveticaBold);
  const oblique = await pdf.embedFont(StandardFonts.HelveticaOblique);

  let pageNum = 1;
  let page    = pdf.addPage([PAGE_W, PAGE_H]);
  let cursor  = drawHeader(page, bold, regular);

  // -- Campaign headline ------------------------------------------------------
  cursor -= 10;
  page.drawText(trunc(campaign.name, 55), {
    x: MARGIN, y: cursor, font: bold, size: 17, color: C.dark,
  });
  cursor -= 18;
  page.drawText(`Status: ${campaign.status}`, {
    x: MARGIN, y: cursor, font: regular, size: 9, color: C.muted,
  });
  if (campaign.location) {
    const locLabel = `\u{1F4CD} ${trunc(campaign.location, 60)}`;
    page.drawText(locLabel, {
      x: MARGIN + 140, y: cursor, font: regular, size: 9, color: C.muted,
    });
  }
  cursor -= 12;
  page.drawText(`Generated ${generatedAt.toISOString().slice(0, 10)}`, {
    x: MARGIN, y: cursor, font: oblique, size: 8, color: C.muted,
  });
  cursor -= 26;

  // -- Summary stat cards -----------------------------------------------------
  const totalCo2 = input.speciesBreakdown
    ? input.speciesBreakdown.reduce((s, e) => s + e.co2KgPerYear, 0)
    : campaign.treeCount * CO2_KG_PER_TREE_PER_YEAR;

  const cardW   = (CW - 24) / 4;
  const cards: [string, string, typeof C.primary][] = [
    ["Trees planted",     campaign.treeCount.toLocaleString(),           C.primary],
    ["CO\u2082 / year",  `${totalCo2.toFixed(1)} kg`,                   C.green  ],
    ["Sponsors",          campaign.sponsorCount.toLocaleString(),        C.primary],
    ["Raised / Goal",     `${campaign.raisedAmount} / ${campaign.goalAmount}`, C.dark],
  ];
  cards.forEach(([label, value, color], i) => {
    statCard(page, bold, regular, MARGIN + i * (cardW + 8), cursor, cardW, label, value, color);
  });
  cursor -= 66;

  drawRule(page, cursor);
  cursor -= 20;

  // -- Species breakdown ------------------------------------------------------
  const breakdown: SpeciesBreakdownEntry[] = input.speciesBreakdown ?? (
    campaign.treeCount > 0
      ? [{ species: "Mixed species", count: campaign.treeCount, co2KgPerYear: totalCo2 }]
      : []
  );

  if (breakdown.length > 0) {
    page.drawText("Species breakdown", { x: MARGIN, y: cursor, font: bold, size: 12, color: C.dark });
    cursor -= 18;

    // Column headers
    const cols = [
      { label: "Species",        x: MARGIN,       w: 180 },
      { label: "Trees",          x: MARGIN + 188, w: 70  },
      { label: "CO\u2082 / yr (kg)", x: MARGIN + 266, w: 100 },
      { label: "% of forest",    x: MARGIN + 374, w: 90  },
    ];
    cols.forEach(col => {
      page.drawText(col.label, { x: col.x, y: cursor, font: bold, size: 8, color: C.muted });
    });
    cursor -= 6;
    drawRule(page, cursor);
    cursor -= 14;

    const totalTrees = breakdown.reduce((s, e) => s + e.count, 0) || 1;
    for (const entry of breakdown) {
      if (cursor < 60) {
        drawFooter(page, regular, pageNum++);
        page   = pdf.addPage([PAGE_W, PAGE_H]);
        cursor = drawHeader(page, bold, regular) - 18;
        page.drawText("Species breakdown (continued)", { x: MARGIN, y: cursor, font: bold, size: 12, color: C.dark });
        cursor -= 22;
      }
      const pct = ((entry.count / totalTrees) * 100).toFixed(1);
      page.drawText(trunc(entry.species, 28), { x: cols[0].x, y: cursor, font: regular, size: 9, color: C.dark });
      page.drawText(entry.count.toLocaleString(),          { x: cols[1].x, y: cursor, font: regular, size: 9, color: C.dark });
      page.drawText(entry.co2KgPerYear.toFixed(1),         { x: cols[2].x, y: cursor, font: regular, size: 9, color: C.green });
      page.drawText(`${pct}%`,                             { x: cols[3].x, y: cursor, font: regular, size: 9, color: C.muted });
      cursor -= 16;
    }
    cursor -= 10;
    drawRule(page, cursor);
    cursor -= 20;
  }

  // -- Sponsor list -----------------------------------------------------------
  const MAX_SPONSORS = 200;
  const sponsors: SponsorRecord[] = campaign.sponsors.slice(0, MAX_SPONSORS);

  if (sponsors.length > 0) {
    if (cursor < 100) {
      drawFooter(page, regular, pageNum++);
      page   = pdf.addPage([PAGE_W, PAGE_H]);
      cursor = drawHeader(page, bold, regular) - 18;
    }

    page.drawText("Sponsors", { x: MARGIN, y: cursor, font: bold, size: 12, color: C.dark });
    cursor -= 18;
    const sCols = [
      { label: "Sponsor address", x: MARGIN,       w: 260 },
      { label: "Amount",          x: MARGIN + 268, w: 100 },
      { label: "Token",           x: MARGIN + 376, w: 70  },
      { label: "Date",            x: MARGIN + 454, w: 80  },
    ];
    sCols.forEach(col => {
      page.drawText(col.label, { x: col.x, y: cursor, font: bold, size: 8, color: C.muted });
    });
    cursor -= 6;
    drawRule(page, cursor);
    cursor -= 14;

    for (const sponsor of sponsors) {
      if (cursor < 60) {
        drawFooter(page, regular, pageNum++);
        page   = pdf.addPage([PAGE_W, PAGE_H]);
        cursor = drawHeader(page, bold, regular) - 18;
        page.drawText("Sponsors (continued)", { x: MARGIN, y: cursor, font: bold, size: 12, color: C.dark });
        cursor -= 22;
      }
      const date = new Date(sponsor.sponsoredAt).toISOString().slice(0, 10);
      page.drawText(trunc(sponsor.address, 38), { x: sCols[0].x, y: cursor, font: regular, size: 8, color: C.dark });
      page.drawText(trunc(sponsor.amount, 14),  { x: sCols[1].x, y: cursor, font: regular, size: 8, color: C.dark });
      page.drawText(trunc(sponsor.token, 8),    { x: sCols[2].x, y: cursor, font: regular, size: 8, color: C.muted });
      page.drawText(date,                        { x: sCols[3].x, y: cursor, font: regular, size: 8, color: C.muted });
      cursor -= 14;
    }

    if (campaign.sponsors.length > MAX_SPONSORS) {
      cursor -= 6;
      page.drawText(
        `… and ${(campaign.sponsors.length - MAX_SPONSORS).toLocaleString()} more sponsors`,
        { x: MARGIN, y: cursor, font: oblique, size: 8, color: C.muted },
      );
      cursor -= 14;
    }

    cursor -= 6;
    drawRule(page, cursor);
    cursor -= 20;
  }

  // -- Optional location map --------------------------------------------------
  if (input.locationMapBytes && input.locationMapFormat) {
    const mapH = 180;
    const mapW = CW;
    if (cursor - mapH < 60) {
      drawFooter(page, regular, pageNum++);
      page   = pdf.addPage([PAGE_W, PAGE_H]);
      cursor = drawHeader(page, bold, regular) - 18;
    }
    page.drawText("Location", { x: MARGIN, y: cursor, font: bold, size: 12, color: C.dark });
    cursor -= 18;
    const img = input.locationMapFormat === "png"
      ? await pdf.embedPng(input.locationMapBytes)
      : await pdf.embedJpg(input.locationMapBytes);
    page.drawImage(img, { x: MARGIN, y: cursor - mapH, width: mapW, height: mapH });
    cursor -= mapH + 14;
  }

  drawFooter(page, regular, pageNum);
  return pdf.save();
}
